name: ensaro
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.4.1
  flutter_bloc: ^8.1.2
  http: ^0.13.6
  equatable: ^2.0.5
  shared_preferences: ^2.1.0
  connectivity_plus: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true